#!/bin/bash
# functions/setup_application.sh
# Setup ZaaNet application and configuration

setup_application() {
    log "📱 Setting up ZaaNet application..."
    
    # =============================================================================
    # CREATE DIRECTORY STRUCTURE
    # =============================================================================
    
    create_directory_structure() {
        log "Creating directory structure..."
        
        local directories=(
            "$ZAANET_DIR"
            "$ZAANET_DIR/app"
            "$ZAANET_DIR/scripts"
            "$ZAANET_DIR/configs"
            "$ZAANET_DIR/logs"
            "$ZAANET_DIR/data"
            "$ZAANET_DIR/backups"
            "$ZAANET_DIR/tmp"
        )
        
        for dir in "${directories[@]}"; do
            if mkdir -p "$dir"; then
                log "✓ Created: $dir"
            else
                error "Failed to create directory: $dir"
            fi
        done
    }
    
    # =============================================================================
    # DOWNLOAD APPLICATION
    # =============================================================================
    
    download_application() {
        if [[ -d "$ZAANET_DIR/app/.git" ]]; then
            log "Updating existing ZaaNet application..."
            cd "$ZAANET_DIR/app" || error "Cannot access app directory"
            
            if git pull; then
                success "✓ Application updated"
            else
                warning "Failed to update application - continuing with current version"
            fi
        else
            log "Downloading ZaaNet application..."
            
            # Remove any existing files
            rm -rf "$ZAANET_DIR/app"/*
            
            if git clone "$GITHUB_REPO" "$ZAANET_DIR/app"; then
                success "✓ Application downloaded"
            else
                error "Failed to download ZaaNet application. Check internet connection and repository URL: $GITHUB_REPO"
            fi
        fi
    }
    
    # =============================================================================
    # INSTALL NODE DEPENDENCIES
    # =============================================================================
    
    install_node_dependencies() {
        log "Installing Node.js dependencies..."
        
        cd "$ZAANET_DIR/app" || error "Cannot access app directory"
        
        # Check if package.json exists
        if [[ ! -f "package.json" ]]; then
            error "package.json not found in application directory"
        fi
        
        # Install dependencies
        if npm install --production; then
            success "✓ Node.js dependencies installed"
        else
            error "Failed to install Node.js dependencies"
        fi
    }
    
    # =============================================================================
    # CREATE ENVIRONMENT CONFIGURATION
    # =============================================================================
    
    create_environment_config() {
        log "Creating environment configuration..."
        
        local env_file="$ZAANET_DIR/app/.env"
        
        cat > "$env_file" <<EOF
# ZaaNet Configuration - Auto-generated by installer
# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

# =============================================================================
# NETWORK CONFIGURATION
# =============================================================================
PORTAL_IP=$PORTAL_IP
PORTAL_PORT=$PORTAL_PORT
PORTAL_DOMAIN=$PORTAL_DOMAIN
WIRELESS_INTERFACE=$WIRELESS_INTERFACE
ETHERNET_INTERFACE=$ETHERNET_INTERFACE
DNS_SERVER=$DNS_SERVER

# =============================================================================
# WIFI HOTSPOT SETTINGS
# =============================================================================
WIFI_SSID=$WIFI_SSID
DHCP_START=$DHCP_START
DHCP_END=$DHCP_END

# =============================================================================
# SERVICE CONFIGURATION
# =============================================================================
CONTRACT_ID=$CONTRACT_ID
MAIN_SERVER_URL=$MAIN_SERVER_URL
NODE_ENV=production

# =============================================================================
# SYSTEM INFORMATION
# =============================================================================
INSTALLER_VERSION=1.0.0
INSTALL_DATE="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
DEVICE_MODEL=${DEVICE_MODEL:-Unknown}
DEVICE_TYPE=${DEVICE_TYPE:-Unknown}

# =============================================================================
# PATHS
# =============================================================================
ZAANET_DIR=$ZAANET_DIR
LOG_DIR=$ZAANET_DIR/logs
DATA_DIR=$ZAANET_DIR/data
CONFIG_DIR=$ZAANET_DIR/configs
EOF
        
        # Set proper permissions
        chmod 600 "$env_file"
        
        success "✓ Environment configuration created"
    }
    
    # =============================================================================
    # CREATE APPLICATION CONFIG
    # =============================================================================
    
    create_app_config() {
        log "Creating application configuration..."
        
        local config_file="$ZAANET_DIR/configs/zaanet.json"
        
        cat > "$config_file" <<EOF
{
  "version": "1.0.0",
  "contract_id": "$CONTRACT_ID",
  "network": {
    "ssid": "$WIFI_SSID",
    "portal_ip": "$PORTAL_IP",
    "portal_port": $PORTAL_PORT,
    "portal_domain": "$PORTAL_DOMAIN",
    "wireless_interface": "$WIRELESS_INTERFACE",
    "ethernet_interface": "$ETHERNET_INTERFACE",
    "dhcp_range": {
      "start": "$DHCP_START",
      "end": "$DHCP_END"
    },
    "dns_server": "$DNS_SERVER"
  },
  "server": {
    "main_url": "$MAIN_SERVER_URL"
  },
  "system": {
    "install_date": "$(date -u '+%Y-%m-%d %H:%M:%S UTC')",
    "device_type": "${DEVICE_TYPE:-Unknown}",
    "auto_start": "${AUTO_START:-yes}"
  },
  "paths": {
    "app_dir": "$ZAANET_DIR/app",
    "log_dir": "$ZAANET_DIR/logs",
    "data_dir": "$ZAANET_DIR/data",
    "config_dir": "$ZAANET_DIR/configs"
  }
}
EOF
        
        success "✓ Application configuration created"
    }
    
    # =============================================================================
    # VERIFY APPLICATION
    # =============================================================================
    
    verify_application() {
        log "Verifying application setup..."
        
        local required_files=(
            "$ZAANET_DIR/app/package.json"
            "$ZAANET_DIR/app/.env"
            "$ZAANET_DIR/configs/zaanet.json"
        )
        
        for file in "${required_files[@]}"; do
            if [[ -f "$file" ]]; then
                log "✓ Found: $(basename "$file")"
            else
                error "Missing required file: $file"
            fi
        done
        
        # Test Node.js app can start
        cd "$ZAANET_DIR/app" || error "Cannot access app directory"
        
        if [[ -f "app.js" ]] || [[ -f "index.js" ]] || [[ -f "server.js" ]]; then
            success "✓ Application entry point found"
        else
            warning "No standard entry point found (app.js, index.js, server.js)"
        fi
    }
    
    # =============================================================================
    # RUN SETUP STEPS
    # =============================================================================
    
    create_directory_structure
    download_application
    install_node_dependencies
    create_environment_config
    create_app_config
    verify_application
    
    success "✅ ZaaNet application setup completed"
}
